### ISSUE TITLE
Unorthodox way of reaching you? :)

### ISSUE THREAD

**Issue by bivald** [FabianLars/FabianLars#1]
I'm looking for a rust freelancer for a project I'm working on, but couldn't find your email. Would you be interested in hearing more? You can see my profile at https://github.com/bivald and reach me via that :)

**Comment by FabianLars** [comment]
Hello 👋 Thank you for reaching out to me :) I am currently employed full-time and not looking for any other jobs at this time. Thanks again and good luck!
